from sklearn.discriminant_analysis import (
    QuadraticDiscriminantAnalysis as QuadraticDiscriminantAnalysisOperation,
)

from DashAI.back.core.schema_fields import (
    schema_field,
    float_field,
    bool_field,
)

from DashAI.back.core.schema_fields.base_schema import BaseSchema
from DashAI.back.converters.scikit_learn.sklearn_like_converter import (
    SklearnLikeConverter,
)


class QuadraticDiscriminantAnalysisSchema(BaseSchema):
    # priors: schema_field(
    #     none_type(float_field()), # array-like of shape (n_classes,)
    #     None,
    #     "Class priors.",
    # )  # type: ignore
    reg_param: schema_field(
        float_field(ge=0.0),
        0.0,
        "Regularization parameter.",
    )  # type: ignore
    store_covariance: schema_field(
        bool_field(),
        False,
        "If True, the covariance matrices are computed and stored in the `covariance_` attribute.",
    )  # type: ignore
    tol: schema_field(
        float_field(ge=0.0),
        1e-4,
        "Tolerance for the stopping condition.",
    )  # type: ignore


class QuadraticDiscriminantAnalysis(
    SklearnLikeConverter, QuadraticDiscriminantAnalysisOperation
):
    """Scikit-learn's QuadraticDiscriminantAnalysis wrapper for DashAI."""

    SCHEMA = QuadraticDiscriminantAnalysisSchema
    DESCRIPTION = "A classifier with a quadratic decision boundary, generated by fitting class conditional densities to the data and using Bayes' rule."
